# Generated by Django 4.0.5 on 2022-07-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('nacionalidad', models.CharField(choices=[('(Ecuatoriana)', 'Ecuatoriana'), ('(Peruana)', 'Peruana'), ('(Colombiana)', 'Colombiana')], max_length=30, verbose_name='Apellido')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_dep', models.DecimalField(decimal_places=2, max_digits=100)),
                ('num_cuartos', models.IntegerField()),
                ('num_banos', models.IntegerField()),
                ('valor_ali', models.DecimalField(decimal_places=2, max_digits=100)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='administrativo.propietario')),
            ],
        ),
    ]
